### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by dereuromark** [cakephp/twig-view#13]
Shall we at least make a beta release here?

I am wondering if I need/should switch over the Dto plugin:
https://github.com/dereuromark/cakephp-dto/blob/cake4/composer.json#L32 ( => https://github.com/dereuromark/cakephp-dto/pull/27 )

**Comment by othercorey** [comment]
I'm going to try and convert the configure-by-event events to Configure + override methods. If that doesn't seem likely, then I'll post.

**Comment by ADmad** [comment]
@dereuromark Creating issues for release seems unnecessary. You can instead use the "Projects" feature to maintain list of tasks that need to be completed to be ready for release.

**Comment by othercorey** [comment]
Ready for beta.
