### ISSUE TITLE
Improve helper integration so templates don't need raw

### ISSUE THREAD

**Issue by markstory** [cakephp/twig-view#14]
Currently all helper output needs to be passed through the `raw` filter. For example:

```twig
{{ Html.link('View this thig', "https://example.com/")|raw }}
```

This is not idea as it trains people to use `raw` which is an unsafe practice. Instead it would be better if we didn't have to use `raw`. This might require generating [twig functions](https://twig.symfony.com/doc/2.x/advanced.html#id2) for each helper method or using a runtime extension that works with the compile steps to generate extension methods.

**Comment by ADmad** [comment]
Would syntax like be acceptable:
```
{{ helper_Html_link('View this thig', "https://example.com/") }}
```

**Comment by othercorey** [comment]
I think we would need a single 'helper' function that wraps everything. I can't imagine generating them for everything.

**Comment by ADmad** [comment]
All Cake helper functions can be handled by single TwigFunction.

**Comment by othercorey** [comment]
Right, that's what I was saying. We agree?

**Comment by ADmad** [comment]
Yes.

We need to decided if we prefer usage like the one I showed above or like:
```
{{ helper('Html.link', 'View this thig', "https://example.com/") }}
```

**Comment by dereuromark** [comment]
The `helper('Html.link'` syntax would have the advantage to auto work with newly added methods right?
Lets say the core adds a new foo() method, would that auto-work here then as `helper('Html.foo', ...)` ?
Or does the plugin/extensions need adjustment for all new ones always?

**Comment by ADmad** [comment]
@dereuromark Both alternatives I showed will work for all helpers methods, of core as well as app/plugins. User land code won't need anything special.

**Comment by ADmad** [comment]
The `helper_Html_link` type naming would use pattern `helper_*` with the help of [dynamic helper](https://twig.symfony.com/doc/3.x/advanced.html#dynamic-filters) feature.

Though I am not sure if using twig functions will work if the Cake helper has for e.g. call to `View::element()`.

**Comment by othercorey** [comment]
We would need to parse the helper name with either implementation, correct?
