### ISSUE TITLE
Use function notation for elements and cells

### ISSUE THREAD

**Issue by othercorey** [cakephp/twig-view#22]
Instead of:
```
{% element 'Plugin.Element' {
    dataName: 'dataValue'
} {
    optionName: 'optionValue'
} %}
```

Use something like:
```
{{ element('Plugin.Element', data=[], options=[]) }}
```

With this you can assign the output to variables or echo directly in a cleaner way. This also lets you clarify data and options using named parameters.

**Comment by ADmad** [comment]
BTW one already use `{{ _view.element('foo') }}` right now, so if were to add a function it would be just to save typing about 6 chars.

**Comment by ADmad** [comment]
Actually need `{{ _view.element('foo')|raw }}` right now so a custom would avoid having to add `|raw`.

**Comment by ADmad** [comment]
I am wrong again, using `_view.element('foo')` most likely won't work since the element file won't be compiled.

**Comment by markstory** [comment]
:+1: To having twig functions for element() and cell(). Needing to use `_view.element()|raw` is tedious and more verbose.
