### ISSUE TITLE
Twig's native format filter is being overwritten

### ISSUE THREAD

**Issue by biesbjerg** [cakephp/twig-view#55]
Twig's native [`format`](https://twig.symfony.com/doc/3.x/filters/format.html) filter is being overwritten by: https://github.com/cakephp/twig-view/blob/e3e03ae99e3bc93ec481eed0a2b0cb92aac13d0b/src/Twig/Extension/NumberExtension.php#L43.

`Number::format` is already being made available by `number_format`, so maybe the other one could be removed?
https://github.com/cakephp/twig-view/blob/e3e03ae99e3bc93ec481eed0a2b0cb92aac13d0b/src/Twig/Extension/NumberExtension.php#L40

**Comment by ADmad** [comment]
Would you like to submit a fix?

**Comment by biesbjerg** [comment]
Opened a PR: https://github.com/cakephp/twig-view/pull/56

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/twig-view/pull/56
